# Data Structures

## Album (object)

+ id: 1 (number)
+ name: Damnation (string, required)
+ type: foo (enum)
    + foo (string)
    + bar (string)
+ read: true (boolean)

## Artist (object)

+ id: 1 (number)
+ name: Damnation (string, required)
+ type: foo (enum)
    + foo (string)
    + bar (string)
+ read: true (boolean)
