# Data Structures

## Album (object)

+ id: 1 (number)
+ name: Damnation (string, required)
+ artist (Artist)
+ type: foo (enum)
    + foo (string)
    + bar (string)
+ is_compilation: true (boolean)

## Artist (object)

+ id: 1 (number)
+ name: Opeth (string, required)
